trainer:
  gpus: 1
  min_epochs: 10
  max_epochs: 25
  benchmark: True
experiment:
  task: "resisc45"
  module:
    loss: "ce"
    classification_model: "resnet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    weights: "imagenet"
    in_channels: 3
    num_classes: 45
  datamodule:
    root_dir: "data/"
    batch_size: 128
    num_workers: 4