trainer:
  gpus: 1
  min_epochs: 10
  max_epochs: 50
  benchmark: True
experiment:
  task: "eurosat-robust"
  module:
    loss: "bce"
    classification_model: "resnet50"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    weights: "imagenet"
    in_channels: 13
    num_classes: 10
  datamodule:
    root_dir: "data/"
    batch_size: 64
    num_workers: 4
    cutmix: True
swa_lrs: 1E-2